### ISSUE TITLE
AttributeError: 'HLineBuilder' object has no attribute 'y_final'

### ISSUE THREAD

**Issue by SamuelGreenrod** [camillilab/analyze_clusters#2]
Hi there,

I'm running analyse_clusters using the default data and I keep getting the error message:

Loaded 1 accession numbers.
Cleaning results for FN545816...Done.
Making directory at /mnt/lustre/users/steg500/IS_element_analysis/Carrie/Redo_for_paper/inversion/analyze_clusters/Cluster Data/FN545816...
Making directory at /mnt/lustre/users/steg500/IS_element_analysis/Carrie/Redo_for_paper/inversion/analyze_clusters/Cluster Data/FN545816/Gene Diagrams...
Making directory at /mnt/lustre/users/steg500/IS_element_analysis/Carrie/Redo_for_paper/inversion/analyze_clusters/Cluster Data/FN545816/Cluster Graphs...
Parsing GenBank data...3543 CDS detected in organism Clostridioides difficile R20291.
Loading /mnt/lustre/users/steg500/IS_element_analysis/Carrie/Redo_for_paper/inversion/analyze_clusters/SOR Data/FN545816_sor.csv as SOR data...31839 locations loaded with 37062 reads.
Loading /mnt/lustre/users/steg500/IS_element_analysis/Carrie/Redo_for_paper/inversion/analyze_clusters/sCLIP Data/FN545816_sclip.csv as sCLIP data...31839 locations loaded with 37062 reads.
Creating thresholder for SOR data with 5000nt bins...
Traceback (most recent call last):
  File "detect_inversion_clusters.py", line 136, in <module>
    main()
  File "detect_inversion_clusters.py", line 79, in main
    clusters = bug.make_SOR_interactive_graphical_threshold(automatic=config.is_automatic)
  File "/mnt/lustre/users/steg500/IS_element_analysis/Carrie/Redo_for_paper/inversion/analyze_clusters/cluster_tools.py", line 217, in make_SOR_interactive_graphical_threshold
    self.SOR_read_cutoff = r.y_final
AttributeError: 'HLineBuilder' object has no attribute 'y_final'

Do you have any idea how to fix this? Thank you!

**Comment by camillilab** [comment]
Hello,

Try clicking on the graph to draw a horizontal line, then closing the graph - it looks like no y_final value is set using manual thresholding.
